### PR TITLE
A Real "FullPage" screenshots

### PR DESCRIPTION
**Pull request by theKashey**
By default "fullPage" screenshots are not working :(
The reason is simply - the "real" page is shown inside iFrame and content is invisible below the fold.
The "right" way to fix it - open `iframe.html` and shoot that page. I've tried to do it, but as result all images were the same.

So this is a "fix" to the "old" approach - just propagating dimensions from the internal iframe, and shooting that iframe.
As result, if an element is smaller that 100vh - only required height will be saved, thus saving time and space.

### CODE REVIEW

**Comment by tsuyoshiwada** [comment]
Hi @theKashey, Thank you for PR :smiley:

Have you tested successfully in your environment ??

---

When I run the test locally, it seems that the following error occurs.

```
{ Error: Protocol error (Runtime.evaluate): Cannot find context with specified id undefined
    at Promise (/Users/tsuyoshiwada/develop/storybook-chrome-screenshot/node_modules/puppeteer/lib/Connection.js:198:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/tsuyoshiwada/develop/storybook-chrome-screenshot/node_modules/puppeteer/lib/Connection.js:197:12)
    at ExecutionContext.evaluateHandle (/Users/tsuyoshiwada/develop/storybook-chrome-screenshot/node_modules/puppeteer/lib/ExecutionContext.js:65:77)
    at _documentPromise._contextPromise.then (/Users/tsuyoshiwada/develop/storybook-chrome-screenshot/node_modules/puppeteer/lib/FrameManager.js:319:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  message: 'Protocol error (Runtime.evaluate): Cannot find context with specified id undefined' }
```

Thanks.

**Comment by theKashey** [comment]
For tests are green, and I've also tested it against some real books, and it's fine, more or less.
> Less is about - it is better to shot not the page(or iframe) itself, but content of `withStorybook`, as long some of mine stories contain some "interface" around, which should not be a part of an image.

Let me double check this branch yet again.

**Comment by theKashey** [comment]
I was using puppeteer 1.3.0, while you used 1.2.0.
Just bumped it 1.4.0, and merged with the current master - tests are green.

**Comment by tsuyoshiwada** [comment]
Thanks! I could confirm tha the tests is green!
But, React's test seems to be failing ... (It is a mistake of bash script :innocent:)

```
 LAUNCH  Launching storybook server ...
 PREPARE  Fetching the target components ...
 CAPTURE  Capturing component screenshots ...

📷  [================                        ] 9/23

 ERROR  An unexpected error occurred, Please make sure message below
Error: Protocol error (Runtime.evaluate): Cannot find context with specified id undefined
```

After shooting about 7 to 9 screenshots, it seems that the same error as before occurs.

**Comment by theKashey** [comment]
So tests are green, but something is broken in real?

**Comment by tsuyoshiwada** [comment]
@theKashey I'm sorry I got a response late... :sob:

---

> So tests are green, but something is broken in real?

Yes. If you run the following command, it seems that the `react` test failed.

```bash
$ yarn test:e2e
```

**Comment by theKashey** [comment]
So that was a real exceptions, which are not introduced by this PR, so I am not going to pursue them in this PR.
The problem was simple - storybook preview was empty, ie there was no iframe to capture.

current version will take a screen shot of the whole page (it will be blank, indeed), but not fail.

**Comment by theKashey** [comment]
And done!

**Comment by tsuyoshiwada** [comment]
@theKashey 
Thank you for many contribution!!
Released as `1.1.0` :tada:

**Comment by theKashey** [comment]
One ready, two to go!

**Pull request merged**
