### PR TITLE
Fix capturing process in the big projects

### PR DESCRIPTION
**Pull request by alexeybondarenko**
Hi. Sorry that I didn't publish this PR earlier. It's related to this issue https://github.com/tsuyoshiwada/storybook-chrome-screenshot/issues/10

I've remade the capturing process to avoid the race conditions. I've added additional decorator `initDecorator` that allows us to detect the finish of the mounting of the stories and therefore we can remove render timeout.

I use this plugin for 1 month in the [Syft](https://syftapp.com). It works nice.
I would like to add in the future these improvements:
- [ ] better handle the finish of the rendering of the custom fonts
- [ ] support fullPage flag to be capture full page and not cut the story by the viewport

But now, it works now. Our storybook has 120+ stories. We'are capturing them with this plugin and upload to the Argos Ci for the visual regression testing. 

I would be appreciated if you review this PR.

### CODE REVIEW

**Comment by tsuyoshiwada** [comment]
Hi @alexeybondarenko, Thank you for PR :smiley:
Although it may take a while, I will check it, so it will be appreciated if you wait for a while :+1:

**Comment by alexeybondarenko** [comment]
@tsuyoshiwada thanks. Contact me If you need some help during the review 😃

**Comment by alexeybondarenko** [comment]
Thanks 🙂 I will remove it before merge. lib is there now to be able to fetch and use fork via npm

**Comment by tsuyoshiwada** [comment]
@alexeybondarenko Your welcome :ok_hand:

> lib is there now to be able to fetch and use fork via npm

I understood it :+1:

---

I'd like to merge, so can you remove `lib` ?
Also, it is helpful if you can add the content of `initScreenshot` in the document if possible :pray:

**Comment by alexeybondarenko** [comment]
@tsuyoshiwada thanks! Okay, I will update docs and remove lib today 👍

**Comment by tsuyoshiwada** [comment]
@alexeybondarenko Thanks :laughing: !

**Comment by alexeybondarenko** [comment]
@tsuyoshiwada updated :)

**Comment by tsuyoshiwada** [comment]
@alexeybondarenko Thanks! Merged :+1:

**Pull request merged**
